mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi
# Uncomment this block to enable audio recording
#   output_args:
#     record: preset-record-generic-audio-aac

record:
  enabled: true
  retain:
    days: 15
    mode: motion
  preview:
    quality: medium

detectors:
  coral1:
    type: edgetpu
    device: usb

cameras:
  outside-server-room:
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.9.3.100/:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.9.3.100/:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
  outside-kitchen:
    ffmpeg:
      inputs:
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.9.3.101/:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: 
            rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.9.3.101/:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
#  outside-scn-room:
#    ffmpeg:
#      inputs:
#        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.9.3.102/:554/cam/realmonitor?channel=1&subtype=1
#          roles:
#            - detect
#        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.9.3.102/:554/cam/realmonitor?channel=1&subtype=0
#          roles:
#            - record
#  floodlight:
#    ffmpeg:
#      inputs:
#        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.9.3.103/Preview_01_sub
#          roles:
#            - detect
#        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.9.3.103/Preview_01_main
#          roles:
#            - record

version: 0.15-0
